### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by JahanzaibMazhar** [rvspt/QlikSenseGovernance#2]
Hello, I am having a certificate issue in this :

'path to project ':// node apps-info.js -c 'client.pfx' -ud 'UserDirectory' -un 'username'

But I am receiving an error : "unable to verify the first certificate". I have already exported the certificate and pasted it in the root folder of this project. Any suggestion?

**Comment by rvspt** [comment]
Hello, are you exporting both pfx and pem certificates? It will need both.

By the way, if the certificates are in the project folder, you don't need to specify their path, it will look there by default. If you want to specify the path, give it the absolute path instead of a relative one. It is not expecting a relative one :-)

**Comment by JahanzaibMazhar** [comment]
Hi Renato,

Yes i am exporting both pfx and pem certificate but it's still not working, error is "unable to verify the first certificate" 
![app governance issue](https://cloud.githubusercontent.com/assets/24826265/21595356/f44e7ce2-d14e-11e6-995f-b74ecc0779cd.PNG)

![app governance issue2](https://cloud.githubusercontent.com/assets/24826265/21600650/b51ffee4-d1a1-11e6-909b-03c9808853b9.PNG)

**Comment by rvspt** [comment]
Hum, to which machine name did you export your certificates? Use the -a to force to that name, otherwise default will be localhost. I suspect it might be what's causing the problem here.

**Comment by JahanzaibMazhar** [comment]
I am running the application on a localhost, i have also tried '-a localhost' explicitly but it's the same error "unable to verify the first certificate"

**Comment by rvspt** [comment]
Could you try with the actual machine name instead of localhost to see if it changes the behavior?

**Comment by JahanzaibMazhar** [comment]
I tried and still the same error : "unable to verify the first certificate"

**Comment by JahanzaibMazhar** [comment]
Hi Renato,

Thanks for your help so far, certificate issue has been resolved but now the node application is not getting the list/data of my Qlik Sense apps, kindly see attached screenshots
![app lists](https://cloud.githubusercontent.com/assets/24826265/21670582/1f0895d2-d337-11e6-80c6-5bba71666683.PNG)
![applist 2](https://cloud.githubusercontent.com/assets/24826265/21670592/2da54400-d337-11e6-8569-5ece2922fee6.PNG)

**Comment by rvspt** [comment]
Hello JahanzaibMazhar,

Sorry for the delay. The most probable reason for that issue is that js2xmlparser has changed and some lines should be changed in a significant number of files in the project.

As developments for v2 were undergoing I decided not to change it in this version.

Check the QlikSenseGovernance-v2 branch of the project (https://github.com/rvspt/QlikSenseGovernance/tree/QlikSenseGovernance-v2). This one has new features and and has that issue corrected.

P.S.: the reason this isn't yet on master is that we are creating an installer to ease the installation process, but if you install it manually following the described steps on the documentation you should be fine.

Cheers
